### ISSUE TITLE
recycle::unique_pool needs c++14

### ISSUE THREAD

**Issue by campisano** [steinwurf/recycle#21]
This may be not an issue, however the Readme states that 

> The library uses C++11

however recycle::unique_pool uses make_unique that is from c++14

Could the use of make_unique be replaced to an equivalent c++11 code?

**Comment by mortenvp** [comment]
Hi @campisano I would probably prefer to update the README to say C++14 instead. Are you using it in a C++11 context?

**Comment by mortenvp** [comment]
I've updated the readme to reflect that C++14 is required: 0d1a24325ec9ffb02dbfec5996d2de2a93a9910f

Thanks for reporting :+1:
